---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-operator
  labels:
    app.kubernetes.io/name: pg-operator
    app.kubernetes.io/component: app
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: pg-operator
      app.kubernetes.io/component: app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pg-operator
        app.kubernetes.io/component: app
    spec:
      serviceAccountName: pg-operator
      containers:
        - name: pg-operator
          image: ghcr.io/a-light-win/pg-operator:0.1.0
          command:
            ["kopf", "run", "--all-namespaces", "-m", "a_light.pg_operator"]
          volumeMounts:
            - name: pg-operator-config-volume
              mountPath: /etc/pg-operator
      volumes:
        - name: pg-operator-config-volume
          configMap:
            name: pg-operator-config
