---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pg-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pg-operator-cluster-role
rules:
  # Watch all application that has `pg-operator.a_light.win/database=enabled` label
  # so we can create a new database for them.
  - apiGroups: [""]
    resources: [deployments, replicasets, pods]
    verbs: [list, watch, patch, get]
  # Create a new database for application that has `pg-operator.a_light.win/database=enabled` label
  # and create a secret to save the db owner.
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "patch", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pg-operator-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pg-operator-cluster-role
subjects:
  - kind: ServiceAccount
    name: pg-operator
