---
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Update the builder tag
        run: |
          dockerfile_sha=$(sha256sum Dockerfile.builder | cut -c 1-16)
          poetry_lock_sha=$(sha256sum poetry.lock | cut -c 1-16)
          builder_tag=${dockerfile_sha}-${poetry_lock_sha}
          sed -i 's%pg-operator/builder:[^ ]\+%pg-operator/builder:${builder_tag}%' Dockerfile
          echo "BUILDER_TAG=${builder_tag}" >> $GITHUB_ENV

      - name: Cached builder
        id: cached-builder
        uses: actions/cache@v4
        with:
          path: .cached-builder
          key: builder-${{ env.BUILDER_TAG }}

      - name: Build builder if missing
        if: steps.cached-builder.outputs.cache-hit != 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.builder
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/a-light-win/pg-operator/builder:${{ env.BUILDER_TAG }}
            ghcr.io/a-light-win/pg-operator/builder:${{ github.ref_name }}-latest

      - name: Set cached builder flag
        if: steps.cached-builder.outputs.cache-hit != 'true'
        run: |
          echo "git sha: ${GITHUB_SHA}" >> .cached-builder
          echo "builder tag: ${BUILDER_TAG}" >> .cached-builder

      - name: Set docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/a-light-win/pg-operator
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
