---
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Set up poetry
        uses: snok/install-poetry@v1
        with:
          poetry-version: 1.7.1

      - name: Build
        run: poetry build

      - name: Set env VERSION
        run: echo "VERSION=$(poetry version -s)" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/a-light-win/pg-operator
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          args: --platform linux/amd64,linux/arm64 --build-arg VERSION=$VERSION
          tags: ${{ steps.meta.outputs.tags }}
